### ISSUE TITLE
attachment_simple(): AttributeError encountered trying to upload .txt and .xml files

### ISSUE THREAD

**Issue by embelardo** [urschrei/pyzotero#99]
# General
Platform:  Centos 7
Python version:  Python3.6
Pyzotero version: pyzotero v1.4.3

# Problem description
- What were you trying to do? Trying to upload .txt and .xml files
    - What API call did it involve: zotero.attachment_simple()
    - What error was raised? AttributeError: 'Response' object has no attribute 'get'

# If possible, paste the full traceback in a code block below, and fill in the summary
<details>
    <summary>Traceback</summary>
    
    Traceback (most recent call last):
    File "./upload_zot_items.py", line 251, in <module>
        main()
    File "./upload_zot_items.py", line 247, in main
        parse_jira_xml(args, target_collection_id)
    File "./upload_zot_items.py", line 214, in parse_jira_xml
        item_created = parse_jira_item(args, item_xml, target_collection_id)
    File "./upload_zot_items.py", line 196, in parse_jira_item
        upload_status = upload_file_attachments(item_id, dir_name)
    File "/vagrant/upload_zot_items_web_api.py", line 48, in upload_file_attachments
        ret = zotero.attachment_simple(item_files, item_id)
    File "/usr/lib64/python3.6/site-packages/pyzotero/zotero.py", line 1363, in attachment_simple
        return self._attachment(to_add, parentid)
    File "/usr/lib64/python3.6/site-packages/pyzotero/zotero.py", line 1028, in _attachment
        res = attachment.upload()
    File "/usr/lib64/python3.6/site-packages/pyzotero/zotero.py", line 2012, in upload
        self._create_prelim()
    File "/usr/lib64/python3.6/site-packages/pyzotero/zotero.py", line 1883, in _create_prelim
        backoff = req.get("backoff")
    AttributeError: 'Response' object has no attribute 'get'

</details>

**Comment by urschrei** [comment]
Sorry! Fixed in v1.4.4, released on PyPI.

**Comment by embelardo** [comment]
Thank you very much!
